In [7]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [8]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [26]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-01-06 19:16:21.938083
1  10005  MACHADO  BT50    100     60  z0019_2.csv 2026-01-06 19:16:21.938083
2  10003  ARRUELA  BT20    300    250  z0019_2.csv 2026-01-06 19:16:21.938083

In [29]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP
            )
""")

In [31]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [45]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-01-06 19:10:19.941106
1  10002     PORCA  BT50   200   150  z0019_1.csv 2026-01-06 19:10:19.941106
2  10003   ARRUELA  BT20   300   250  z0019_1.csv 2026-01-06 19:10:19.941106
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-01-06 19:16:21.938083
4  10005   MACHADO  BT50   100    60  z0019_2.csv 2026-01-06 19:16:21.938083

In [44]:
con.execute("ALTER TABLE bronze_z009 RENAME TO bronze_z0019")

In [43]:
con.execute("SELECT * FROM bronze_z009").fetchdf().head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-01-06 19:10:19.941106
1  10002     PORCA  BT50   200   150  z0019_1.csv 2026-01-06 19:10:19.941106
2  10003   ARRUELA  BT20   300   250  z0019_1.csv 2026-01-06 19:10:19.941106
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-01-06 19:16:21.938083
4  10005   MACHADO  BT50   100    60  z0019_2.csv 2026-01-06 19:16:21.938083

In [46]:
con.close()